### ISSUE TITLE
Comments are not getting posted for anonymous users

### ISSUE THREAD

**Issue by jerseycloud** [verbb/comments#135] opened 2019-08-03 22:38 UTC
I am doing my local development on a Windows 10 machine with a WAMPserver. The version of Craft CMS is 3.2.8. I have installed the latest version of Verbb Comments module (1.1.7.1). I am using the "{{ craft.comments.render(entry.id) }}" code in my template to render the HTML, CSS and JavaScript on the front-end.

When I am logged in to the site and submit a comment, that comments gets posted successfully. But when I am not logged in to the site and submit a comment, that comment does not get posted. I looked at the web.log file to see what's going on and I see this logged error message:

2019-08-03 11:02:17 [-][-][-][trace][yii\base\Controller::runAction] Route to run: comments/comments/save
2019-08-03 11:02:17 [-][-][-][error][yii\web\HttpException:503] craft\web\ServiceUnavailableHttpException in C:\Programs\wamp64\my_sites\pofo_spanish_version_1_local\craft_pofo\vendor\craftcms\cms\src\web\Controller.php:163

In my comments.php file, I have enabled anonymous comments. What could be wrong here?

**Comment by qilinksarl** [comment] 2019-08-04 13:46
I've same problem.

**Comment by engram-design** [comment] 2019-08-06 01:42
Duplicate of https://github.com/verbb/comments/issues/133

**Closed as completed by engram-design** 2019-08-06 01:42 UTC
