### ISSUE TITLE
Avatar not shown

### ISSUE THREAD

**Issue by lucosius** [verbb/comments#263] opened 2022-09-22 20:45 UTC
### Question

Hello,

After upgrading to CraftCMS 4 - the user avatar is not being displayed... In the source code I can see that URL is not set into img tag.

I have this code to get avatar url:
```

    {% if comment.can('showAvatar') %}
     {% set avatar = comment.getAvatar() %}
     <div class="comment-item-userpic">
         {% if avatar %}
                    <img src="{{ avatar.url({ width: 65, height: 65, mode: 'fit' }) }}" class="image-cover"/>
                {% else %}
                    <img src="https://telefonai.eu/avatar.jpeg" class="image-cover"/>
                {% endif %}
                                            </div>
    {% endif %}
```

System can see if avatar exist but cannot put URL. What can be wrong here?

**Comment by engram-design** [comment] 2022-09-22 22:09
Likely duplicate of https://github.com/verbb/comments/issues/261 which again, this should've been created as a Bug Report issue, not a question.

What are your asset volume/filesystem settings? What does a `{% dd avatar %}` produce just above the `<img>` tag?

**Comment by lucosius** [comment] 2022-09-28 09:31
I fixed this problem with changing avatar query to this:

` {% set avatar = comment.author.getPhoto() %}`

**Comment by engram-design** [comment] 2022-10-08 03:16
Closing in favour of https://github.com/verbb/comments/issues/264

**Closed as completed by engram-design** 2022-10-08 03:16 UTC
Labels: question
